# MATHS ASSIGNMENT 7 - centhurvelan


In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)
A = np.array([
 [ 4, -2, 2, 1],
 [ 1, 1, 0, 1],
 [-2, 1, 3, -1],
 [ 1, 3, -1, 2]
], dtype=float)
A

array([[ 4., -2.,  2.,  1.],
       [ 1.,  1.,  0.,  1.],
       [-2.,  1.,  3., -1.],
       [ 1.,  3., -1.,  2.]])

1) Calculating the inverse matrix of A

In [9]:
detA = np.linalg.det(A)
A_I = np.linalg.inv(A)
print("det(A) =", detA)
print("A_inverse =\n", A_I)
I_check = A @ A_I
print("\nA @ A_inverse :\n", I_check)

det(A) = -1.0000000000000027
A_inverse =
 [[  5. -30.   1.  13.]
 [  4. -25.   1.  11.]
 [ -1.   7.   0.  -3.]
 [ -9.  56.  -2. -24.]]

A @ A_inverse :
 [[ 1.  0.  0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


2. Calculating Eigenvalues and Eigenvectors

In [11]:
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:\n", eigvals)
print("\nEigenvectors :\n", eigvecs)
idx = np.argsort(-np.abs(eigvals))
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]
print("\n Sorted Eigenvalues:\n", eigvals)
print("\n Corresponding Eigenvectors (columns):\n", eigvecs)

Eigenvalues:
 [-0.022317+0.j        3.610453+1.720341j  3.610453-1.720341j
  2.801411+0.j      ]

Eigenvectors :
 [[-0.436762+0.j        0.575983+0.j        0.575983-0.j
   0.267489+0.j      ]
 [-0.369001+0.j        0.009623-0.210522j  0.009623+0.210522j
  -0.348939+0.j      ]
 [ 0.102397+0.j       -0.008217+0.551423j -0.008217-0.551423j
  -0.061208+0.j      ]
 [ 0.813998+0.j       -0.188691-0.533004j -0.188691+0.533004j
  -0.896072+0.j      ]]

 Sorted Eigenvalues:
 [ 3.610453+1.720341j  3.610453-1.720341j  2.801411+0.j
 -0.022317+0.j      ]

 Corresponding Eigenvectors (columns):
 [[ 0.575983+0.j        0.575983-0.j        0.267489+0.j
  -0.436762+0.j      ]
 [ 0.009623-0.210522j  0.009623+0.210522j -0.348939+0.j
  -0.369001+0.j      ]
 [-0.008217+0.551423j -0.008217-0.551423j -0.061208+0.j
   0.102397+0.j      ]
 [-0.188691-0.533004j -0.188691+0.533004j -0.896072+0.j
   0.813998+0.j      ]]


3. After having the Eigenvalues and Eigenvectors,

    - Constructing the eigen matrix P from eigenvectors: 

    - Constructing the diagonal matrix D from eigenvalues: 

    - Calculating the inverse of the eigen matrix:
  
    - 
    Verify if the diagonalized matrix `A_diagonalized` is identical to the original matrix `A` 


In [12]:
P = eigvecs
D = np.diag(eigvals)
P_inv = np.linalg.inv(P)
A_diagonalized = P @ D @ P_inv
print("P:\n", P)
print("\nD:\n", D)
print("\nP^{-1}:\n", P_inv)
print("\nA_diagonalized:\n", A_diagonalized)
print("\nnp.allclose(A_diagonalized, A)? ->", np.allclose(A_diagonalized, A))  # Fixed: completed the function call
print("Max abs difference:", np.abs(A_diagonalized - A).max())

P:
 [[ 0.575983+0.j        0.575983-0.j        0.267489+0.j
  -0.436762+0.j      ]
 [ 0.009623-0.210522j  0.009623+0.210522j -0.348939+0.j
  -0.369001+0.j      ]
 [-0.008217+0.551423j -0.008217-0.551423j -0.061208+0.j
   0.102397+0.j      ]
 [-0.188691-0.533004j -0.188691+0.533004j -0.896072+0.j
   0.813998+0.j      ]]

D:
 [[ 3.610453+1.720341j  0.      +0.j        0.      +0.j
   0.      +0.j      ]
 [ 0.      +0.j        3.610453-1.720341j  0.      +0.j
   0.      +0.j      ]
 [ 0.      +0.j        0.      +0.j        2.801411+0.j
   0.      +0.j      ]
 [ 0.      +0.j        0.      +0.j        0.      +0.j
  -0.022317+0.j      ]]

P^{-1}:
 [[ 1.00207 +0.017633j -0.26465 -0.062701j  0.269895-0.846129j
   0.383752+0.087477j]
 [ 1.00207 -0.017633j -0.26465 +0.062701j  0.269895+0.846129j
   0.383752-0.087477j]
 [-0.180358+0.j       -1.346121+0.j       -1.067503-0.j
  -0.57271 +0.j      ]
 [ 0.24294 -0.j       -1.522431-0.j        0.058076-0.j
   0.661404-0.j      ]]

A_diagonalized:
 

4)  Explain why this result (a diagonalized matrix is identical to the original matrix) is important in linear algebra (1 pts).

Diagonalization ($A = PDP^{-1}$) is crucial because it simplifies a complex matrix $A$ into a simple diagonal matrix $D$ by viewing it from the "right" perspective (the eigenvectors in $P$).This is vital because it makes complex operations, like calculating high powers ($A^{100}$), incredibly fast and easy. Instead of multiplying $A$ 100 times, you just take the power of $D$'s diagonal entries ($A^{100} = PD^{100}P^{-1}$), which is essential for analyzing dynamic systems and differential equations.

5)  Make a python code using SVD example to get the same A (AR)

  - Decide your own range for the sigma



In [13]:
U, S, Vt = np.linalg.svd(A, full_matrices=True)
print("σ:", S)
def svd_reconstruct(U, S, Vt, r):
 Ur = U[:, :r]
 Sr = np.diag(S[:r])
 Vtr = Vt[:r, :]
 return Ur @ Sr @ Vtr
for r in range(1, 6): 
 A_r = svd_reconstruct(U, S, Vt, r)
 err = np.linalg.norm(A - A_r, ord='fro')
 print(f"r = {r}: ||A - A_r||_F = {err:.6e}")
A_4 = svd_reconstruct(U, S, Vt, 4)
print("\nnp.allclose(A, A_4)? ", np.allclose(A, A_4, atol=1e-10))
print("maximum abs difference (r=5):", np.abs(A - A_4).max())

σ: [5.254937 4.481288 3.209909 0.013229]
r = 1: ||A - A_r||_F = 5.512317e+00
r = 2: ||A - A_r||_F = 3.209937e+00
r = 3: ||A - A_r||_F = 1.322930e-02
r = 4: ||A - A_r||_F = 5.496728e-15
r = 5: ||A - A_r||_F = 5.496728e-15

np.allclose(A, A_4)?  True
maximum abs difference (r=5): 3.552713678800501e-15


In [14]:
!jupyter nbconvert "MATHS_assignment7_Centhur.ipynb" --to webpdf

[NbConvertApp] Converting notebook MATHS_assignment7_Centhur.ipynb to webpdf
[NbConvertApp] Building PDF
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 135861 bytes to MATHS_assignment7_Centhur.pdf
